spring:
  application:
  # 这里表示注册服务的名称
    name: eureka-client
server:
  port: 8201
eureka:
  client:
    serviceUrl:
    #需要注册的注册中心地址 要加上/eureka
    #如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    #如果服务注册中心加入了安全验证，
    #这里配置的地址格式为： http://<username>:<password>@localhost:8761/eureka
    #其中 <username> 为安全校验的用户名；<password> 为该用户的密码
      defaultZone: http://localhost:8100/eureka

